### ISSUE TITLE
mobile user online / offline 

### ISSUE THREAD

**Issue by ffabreti** [dchacke/entangled#237]
@dchacke:
 
Hey Dennis, I have a question about floating mobile user connectivity.
Sorry if the flow is not 100% right, I am still trying to understand it.
Picture this:

1) user-A and user-B are running a Ionic Chat App (cordova + angular)
2) both users connect to `ws://localhost:3000/chatRooms` and `ws://localhost:3000/chatRooms/:chatRoomsId/messages`
3) both users retrieve and subscribe to `chatRooms.all()` 
4) user-A creates a new chatroom with `chatRooms.create()` (id=10)
5) user-B receives updated chatRooms (because it's subscribed to `/chatRooms`)
6) both users enter chatRoom (id=10) with `ChatRooms.find(10)`

7) user-B becomes offline (no network connection)
8) user-A sends a `chatRoom10.messages().create('hello there')`
9) after 10 minutes, user-B becomes online again

Will user-B receive the `"hello there"` message or not?

**Comment by dchacke** [comment]
If you're asking if there's offline support, the answer is: not yet. But it's on my todo list :-) Since it's mentioned in a section in the [Readme](https://github.com/dchacke/entangled#development-priorities), I'll close this issue.

If you need a workaround, what I recommend for now is periodically checking if there is a connection, and once a connection has been re-established, fetch the list of messages anew. That way you'd get any messages you missed out on. My hope is that Entangled will do this automatically in the future.

**Comment by ffabreti** [comment]
Oh, I've missed that readme line...

Workaround seems fine, thanks.

By the way, your coding style and inline comments are awesome.

**Comment by dchacke** [comment]
Thank you :)
